version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto

  api:
    build:
      context: Api
    ports:
    - 8000:8000
    depends_on:
      - mosquitto